/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2_tbd2g3;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import oracle.jdbc.internal.ACProxyable;
import javax.swing.*;
import javax.swing.event.*;

/**
 *
 * @author dfcm9
 */
public class MainScreen extends javax.swing.JFrame {

    boolean Conexion1Y = false; //Variable que indica si la conexion de la base de datos origen fue exitosa
    boolean Conexion2Y = false; //Variable que indica si la conexion de la base de datos destino fue exitosa
    OracleConexion OC;
    ConexionMySQL MC;

    //Credenciales base de datos origen
    String originurl = "";
    String origindbname = "";
    String originport = "";
    String originuser = "";
    String originpass = "";

    //Credenciales base de datos destino
    String destinationurl = "";
    String destinationname = "";
    String destinationport = "";
    String destinationuser = "";
    String destinationpass = "";

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_ConexionesDB = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf_InstanciaOrigen = new javax.swing.JTextField();
        tf_DBNameOrigen = new javax.swing.JTextField();
        tf_PuertoOrigen = new javax.swing.JTextField();
        tf_UserOrigen = new javax.swing.JTextField();
        tf_PassOrigen = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_InstanciaDestino = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_DBNameDestino = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tf_PuertoDestino = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_UserDestino = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tf_PassDestino = new javax.swing.JTextField();
        btn_probarConOrigen = new javax.swing.JButton();
        btn_probarConDestino = new javax.swing.JButton();
        lbl_resultadoConexion1 = new javax.swing.JLabel();
        lbl_resultadoConexion2 = new javax.swing.JLabel();
        btn_salirConexiones = new javax.swing.JButton();
        btn_pedirAyuda = new javax.swing.JButton();
        radio_MYSQLOrigin = new javax.swing.JRadioButton();
        radio_ORACLEOrigin = new javax.swing.JRadioButton();
        radio_MYSQLDestination = new javax.swing.JRadioButton();
        radio_ORACLEDestination = new javax.swing.JRadioButton();
        JD_Ayuda = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        btn_VolverAyuda = new javax.swing.JButton();
        botonesOrigen = new javax.swing.ButtonGroup();
        botonesDestino = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_moveOrToDe = new javax.swing.JButton();
        btn_moveDeToOr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_tablasDbOr = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_tablasDbDe = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        btn_cambiarDb = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        JD_ConexionesDB.setTitle("Configuraciones de Bases de Datos");
        JD_ConexionesDB.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Configuraciones de Bases de Datos");

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 204));
        jLabel9.setText("Base de Datos Origen");

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre Instancia");

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre Base de Datos");

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Puerto");

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre de Usuario");

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Contraseña");

        tf_InstanciaOrigen.setBackground(new java.awt.Color(70, 70, 70));
        tf_InstanciaOrigen.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_InstanciaOrigen.setForeground(new java.awt.Color(255, 255, 255));

        tf_DBNameOrigen.setBackground(new java.awt.Color(70, 70, 70));
        tf_DBNameOrigen.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_DBNameOrigen.setForeground(new java.awt.Color(255, 255, 255));

        tf_PuertoOrigen.setBackground(new java.awt.Color(70, 70, 70));
        tf_PuertoOrigen.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_PuertoOrigen.setForeground(new java.awt.Color(255, 255, 255));

        tf_UserOrigen.setBackground(new java.awt.Color(70, 70, 70));
        tf_UserOrigen.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_UserOrigen.setForeground(new java.awt.Color(255, 255, 255));

        tf_PassOrigen.setBackground(new java.awt.Color(70, 70, 70));
        tf_PassOrigen.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_PassOrigen.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 204));
        jLabel15.setText("Base de Datos Destino");

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nombre Instancia");

        tf_InstanciaDestino.setBackground(new java.awt.Color(70, 70, 70));
        tf_InstanciaDestino.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_InstanciaDestino.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nombre Base de Datos");

        tf_DBNameDestino.setBackground(new java.awt.Color(70, 70, 70));
        tf_DBNameDestino.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_DBNameDestino.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Puerto");

        tf_PuertoDestino.setBackground(new java.awt.Color(70, 70, 70));
        tf_PuertoDestino.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_PuertoDestino.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Nombre de Usuario");

        tf_UserDestino.setBackground(new java.awt.Color(70, 70, 70));
        tf_UserDestino.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_UserDestino.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Contraseña");

        tf_PassDestino.setBackground(new java.awt.Color(70, 70, 70));
        tf_PassDestino.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        tf_PassDestino.setForeground(new java.awt.Color(255, 255, 255));

        btn_probarConOrigen.setBackground(new java.awt.Color(0, 51, 102));
        btn_probarConOrigen.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btn_probarConOrigen.setForeground(new java.awt.Color(255, 255, 255));
        btn_probarConOrigen.setText("Probar Conexión");
        btn_probarConOrigen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_probarConOrigen.setFocusable(false);
        btn_probarConOrigen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_probarConOrigenMouseClicked(evt);
            }
        });

        btn_probarConDestino.setBackground(new java.awt.Color(0, 51, 102));
        btn_probarConDestino.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btn_probarConDestino.setForeground(new java.awt.Color(255, 255, 255));
        btn_probarConDestino.setText("Probar Conexión");
        btn_probarConDestino.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_probarConDestino.setFocusable(false);
        btn_probarConDestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_probarConDestinoMouseClicked(evt);
            }
        });

        lbl_resultadoConexion1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        lbl_resultadoConexion1.setForeground(new java.awt.Color(0, 153, 0));
        lbl_resultadoConexion1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_resultadoConexion1.setText("¡Conexion Exitosa!");

        lbl_resultadoConexion2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        lbl_resultadoConexion2.setForeground(new java.awt.Color(0, 153, 0));
        lbl_resultadoConexion2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_resultadoConexion2.setText("¡Conexion Exitosa!");

        btn_salirConexiones.setBackground(new java.awt.Color(153, 0, 0));
        btn_salirConexiones.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        btn_salirConexiones.setForeground(new java.awt.Color(255, 255, 255));
        btn_salirConexiones.setText("Salir");
        btn_salirConexiones.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_salirConexiones.setFocusable(false);
        btn_salirConexiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirConexionesMouseClicked(evt);
            }
        });

        btn_pedirAyuda.setBackground(new java.awt.Color(0, 102, 153));
        btn_pedirAyuda.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        btn_pedirAyuda.setForeground(new java.awt.Color(255, 255, 255));
        btn_pedirAyuda.setText("Ayuda");
        btn_pedirAyuda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_pedirAyuda.setFocusable(false);
        btn_pedirAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_pedirAyudaMouseClicked(evt);
            }
        });

        radio_MYSQLOrigin.setBackground(new java.awt.Color(51, 51, 51));
        botonesOrigen.add(radio_MYSQLOrigin);
        radio_MYSQLOrigin.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        radio_MYSQLOrigin.setForeground(new java.awt.Color(255, 255, 255));
        radio_MYSQLOrigin.setText("MYSQL");

        radio_ORACLEOrigin.setBackground(new java.awt.Color(51, 51, 51));
        botonesOrigen.add(radio_ORACLEOrigin);
        radio_ORACLEOrigin.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        radio_ORACLEOrigin.setForeground(new java.awt.Color(255, 255, 255));
        radio_ORACLEOrigin.setText("ORACLE");

        radio_MYSQLDestination.setBackground(new java.awt.Color(51, 51, 51));
        botonesDestino.add(radio_MYSQLDestination);
        radio_MYSQLDestination.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        radio_MYSQLDestination.setForeground(new java.awt.Color(255, 255, 255));
        radio_MYSQLDestination.setText("MYSQL");

        radio_ORACLEDestination.setBackground(new java.awt.Color(51, 51, 51));
        botonesDestino.add(radio_ORACLEDestination);
        radio_ORACLEDestination.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        radio_ORACLEDestination.setForeground(new java.awt.Color(255, 255, 255));
        radio_ORACLEDestination.setText("ORACLE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(btn_pedirAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_salirConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btn_probarConOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_probarConDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_resultadoConexion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tf_PuertoOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addGap(199, 199, 199))
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_InstanciaOrigen)
                        .addComponent(tf_DBNameOrigen)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_UserOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addComponent(tf_PassOrigen, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_MYSQLOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_ORACLEOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tf_PuertoDestino)
                            .addGap(199, 199, 199))
                        .addComponent(tf_InstanciaDestino)
                        .addComponent(tf_DBNameDestino)
                        .addComponent(tf_UserDestino)
                        .addComponent(tf_PassDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addComponent(lbl_resultadoConexion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radio_MYSQLDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_ORACLEDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radio_MYSQLOrigin)
                            .addComponent(radio_ORACLEOrigin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(tf_InstanciaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_DBNameOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_PuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_UserOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_PassOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_salirConexiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_pedirAyuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radio_MYSQLDestination)
                                .addComponent(radio_ORACLEDestination))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(tf_InstanciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_DBNameDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_PuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_UserDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_PassDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_probarConOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_probarConDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_resultadoConexion1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_resultadoConexion2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout JD_ConexionesDBLayout = new javax.swing.GroupLayout(JD_ConexionesDB.getContentPane());
        JD_ConexionesDB.getContentPane().setLayout(JD_ConexionesDBLayout);
        JD_ConexionesDBLayout.setHorizontalGroup(
            JD_ConexionesDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_ConexionesDBLayout.setVerticalGroup(
            JD_ConexionesDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        JD_Ayuda.setTitle("Ayuda y Acerca del Programa");

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ayuda y Acerca del Programa");

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("El programa de Conexion de Base de Datos permite el enlazado entre bases de datos, permitiendo hacer  ");

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Para iniciar este proceso, debe conectar dos bases de datos. Una vez que estas esten conectadas, podra ");

        jLabel26.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("accesar al portal de traslado de datos, donde podra copiar tablas, guardar o cancelar sus cambios.");

        jLabel27.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("operaciones como la copia de tablas y el mantenimiento de una bitacora para las operaciones realizadas. ");

        jLabel28.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Si necesita cambiar las bases de datos, puede cambiar las conexiones mediante el boton superior");

        jLabel29.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("del panel principal.");

        btn_VolverAyuda.setBackground(new java.awt.Color(102, 0, 0));
        btn_VolverAyuda.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        btn_VolverAyuda.setForeground(new java.awt.Color(255, 255, 255));
        btn_VolverAyuda.setText("Volver");
        btn_VolverAyuda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_VolverAyuda.setFocusable(false);
        btn_VolverAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VolverAyudaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_VolverAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(27, 27, 27)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btn_VolverAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout JD_AyudaLayout = new javax.swing.GroupLayout(JD_Ayuda.getContentPane());
        JD_Ayuda.getContentPane().setLayout(JD_AyudaLayout);
        JD_AyudaLayout.setHorizontalGroup(
            JD_AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JD_AyudaLayout.setVerticalGroup(
            JD_AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Replicacion de Bases de Datos - Principal");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Replicación de Bases de Datos");

        btn_moveOrToDe.setBackground(new java.awt.Color(0, 51, 102));
        btn_moveOrToDe.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btn_moveOrToDe.setForeground(new java.awt.Color(255, 255, 255));
        btn_moveOrToDe.setText("> > > >");
        btn_moveOrToDe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_moveOrToDe.setFocusable(false);
        btn_moveOrToDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_moveOrToDeMouseClicked(evt);
            }
        });

        btn_moveDeToOr.setBackground(new java.awt.Color(0, 51, 102));
        btn_moveDeToOr.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btn_moveDeToOr.setForeground(new java.awt.Color(255, 255, 255));
        btn_moveDeToOr.setText("< < < <");
        btn_moveDeToOr.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_moveDeToOr.setFocusable(false);
        btn_moveDeToOr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_moveDeToOrMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Base de Datos Origen");

        jl_tablasDbOr.setBackground(new java.awt.Color(70, 70, 70));
        jl_tablasDbOr.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jl_tablasDbOr.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jl_tablasDbOr);

        jl_tablasDbDe.setBackground(new java.awt.Color(70, 70, 70));
        jl_tablasDbDe.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        jl_tablasDbDe.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jl_tablasDbDe);

        jLabel5.setBackground(new java.awt.Color(0, 102, 153));
        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("OriginDB");

        btn_cambiarDb.setBackground(new java.awt.Color(0, 51, 102));
        btn_cambiarDb.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btn_cambiarDb.setForeground(new java.awt.Color(255, 255, 255));
        btn_cambiarDb.setText("Configurar Bases de Datos");
        btn_cambiarDb.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cambiarDb.setFocusable(false);
        btn_cambiarDb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cambiarDbMouseClicked(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(0, 51, 153));
        btn_guardar.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_guardar.setEnabled(false);
        btn_guardar.setFocusable(false);
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(153, 0, 0));
        btn_cancelar.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_cancelar.setEnabled(false);
        btn_cancelar.setFocusable(false);
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tablas Replicadas");

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tablas Sin Replicar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_moveDeToOr, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_moveOrToDe, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cambiarDb, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(367, 367, 367))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cambiarDb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btn_moveOrToDe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_moveDeToOr, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cambiarDbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cambiarDbMouseClicked
        lbl_resultadoConexion1.setText("");
        lbl_resultadoConexion2.setText("");

        this.setVisible(false);
        AbrirVentana(JD_ConexionesDB);

    }//GEN-LAST:event_btn_cambiarDbMouseClicked

    private void btn_salirConexionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirConexionesMouseClicked
        JD_ConexionesDB.dispose();
        this.setVisible(true);
    }//GEN-LAST:event_btn_salirConexionesMouseClicked

    private void btn_pedirAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pedirAyudaMouseClicked
        AbrirVentana(JD_Ayuda);
    }//GEN-LAST:event_btn_pedirAyudaMouseClicked

    private void btn_VolverAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VolverAyudaMouseClicked
        JD_Ayuda.dispose();
    }//GEN-LAST:event_btn_VolverAyudaMouseClicked

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        if (!btn_guardar.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Boton Deshabilitado.\nConecte dos bases de datos primero.");
        } else {
            ArrayList<String> lista = new ArrayList<>();
            ListModel<String> modelo = jl_tablasDbDe.getModel();
            for(int i = 0; i < modelo.getSize(); i++){
                lista.add(modelo.getElementAt(i));
            }//agarrar la lista de los nombres de las tablas a replicar
            
        }
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseClicked
        if (!btn_cancelar.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Boton Deshabilitado.\nConecte dos bases de datos primero.");
        } else {
            //Lo que haria cuando estuviera habilitado.
        }
    }//GEN-LAST:event_btn_cancelarMouseClicked

    private void btn_moveOrToDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_moveOrToDeMouseClicked
        if (!btn_moveOrToDe.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Boton Deshabilitado.\nConecte dos bases de datos primero.");
        } else {
            String selectedItem = jl_tablasDbOr.getSelectedValue();
            if (selectedItem != null) {
                DefaultListModel<String> modelDestino = (DefaultListModel<String>) jl_tablasDbDe.getModel();
                modelDestino.addElement(selectedItem);
                DefaultListModel<String> modelOrigen = (DefaultListModel<String>) jl_tablasDbOr.getModel();
                modelOrigen.removeElement(selectedItem);
            } else {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado nada para mover");
            }
        }
    }//GEN-LAST:event_btn_moveOrToDeMouseClicked

    private void btn_moveDeToOrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_moveDeToOrMouseClicked
        if (!btn_moveDeToOr.isEnabled()) {
            JOptionPane.showMessageDialog(null, "Boton Deshabilitado.\nConecte dos bases de datos primero.");
        } else {
            String selectedItem = jl_tablasDbDe.getSelectedValue();
            if (selectedItem != null) {
                DefaultListModel<String> modelOrigen = (DefaultListModel<String>) jl_tablasDbOr.getModel();
                modelOrigen.addElement(selectedItem);
                DefaultListModel<String> modelDestino = (DefaultListModel<String>) jl_tablasDbDe.getModel();
                modelDestino.removeElement(selectedItem);
            } else {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado nada para mover");
            }
        }
    }//GEN-LAST:event_btn_moveDeToOrMouseClicked

    private void btn_probarConOrigenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_probarConOrigenMouseClicked
        // NOTA: HAY UN LABEL QUE INDICA SI LA CONEXION FUE EXITOSA O NO. FAVOR CAMBIARLO EN BASE AL RESULTADO

        if (radio_ORACLEOrigin.isSelected()) {

            //Oracle
            originurl = tf_InstanciaOrigen.getText();
            origindbname = tf_DBNameOrigen.getText();
            originport = tf_PuertoOrigen.getText();
            originuser = tf_UserOrigen.getText();
            originpass = tf_PassOrigen.getText();

            OC = new OracleConexion();
            Conexion1Y = OC.Conectar(originurl, originuser, originpass, originport);

            if (Conexion1Y) {
                //Logica para determinar que la conexion fue exitosa, pone los nombres de las tablas
                lbl_resultadoConexion1.setText("¡Conexion Exitosa!");
                lbl_resultadoConexion1.setForeground(Color.green);
                lbl_resultadoConexion1.setVisible(true);

                // Obtener nombres de tablas
                List<String> tableNames = OC.getNombresTabla(); // Llama al método que obtendrá los nombres de las tablas

                // Verificar si se obtuvieron tablas
                if (tableNames.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No se encontraron tablas en la base de datos.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Convertir la lista a un array y asignarlo a la JList
                    DefaultListModel<String> listModel = new DefaultListModel<>();
                    for (String tableName : tableNames) {
                        listModel.addElement(tableName);
                    }
                    jl_tablasDbOr.setModel(listModel); // Asignar el modelo a la JList
                }
                
                DefaultListModel<String> listModel2 = new DefaultListModel<>();
                jl_tablasDbDe.setModel(listModel2);
                
                
                System.out.println("Modelo de jl_tablasDbOr: " + jl_tablasDbOr.getModel().getClass());
                System.out.println("Modelo de jl_tablasDbDe: " + jl_tablasDbDe.getModel().getClass());

            } else {
                lbl_resultadoConexion1.setText("¡Ha ocurrido un error!");
                lbl_resultadoConexion1.setForeground(Color.red);
                lbl_resultadoConexion1.setVisible(true);
            }

        } else if (radio_MYSQLOrigin.isSelected()) {

            //MYSQL
            originurl = tf_InstanciaOrigen.getText();
            origindbname = tf_DBNameOrigen.getText();
            originport = tf_PuertoOrigen.getText();
            originuser = tf_UserOrigen.getText();
            originpass = tf_PassOrigen.getText();

            MC = new ConexionMySQL();
            Conexion1Y = MC.conectar(originurl, originuser, originpass, originport, origindbname);

            if (Conexion1Y) {
                //Logica para determinar que la conexion fue exitosa, pone los nombres de las tablas
                lbl_resultadoConexion1.setText("¡Conexion Exitosa!");
                lbl_resultadoConexion1.setForeground(Color.green);
                lbl_resultadoConexion1.setVisible(true);

                // Obtener nombres de tablas
                List<String> tableNames = MC.getNombresTabla(origindbname); // Llama al método que obtendrá los nombres de las tablas

                // Verificar si se obtuvieron tablas
                if (tableNames.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "No se encontraron tablas en la base de datos.",
                            "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Convertir la lista a un array y asignarlo a la JList
                    DefaultListModel<String> listModel = new DefaultListModel<>();
                    for (String tableName : tableNames) {
                        listModel.addElement(tableName);
                    }
                    jl_tablasDbOr.setModel(listModel); // Asignar el modelo a la JList
                }

            } else {
                lbl_resultadoConexion1.setText("¡Ha ocurrido un error!");
                lbl_resultadoConexion1.setForeground(Color.red);
                lbl_resultadoConexion1.setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, primero seleccione (arriba) si su base esta en Oracle o MYSQL");
        }
    }//GEN-LAST:event_btn_probarConOrigenMouseClicked

    private void btn_probarConDestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_probarConDestinoMouseClicked
        // NOTA: HAY UN LABEL QUE INDICA SI LA CONEXION FUE EXITOSA O NO. FAVOR CAMBIARLO EN BASE AL RESULTADO

        if (radio_ORACLEOrigin.isSelected()) {

            //Oracle
            originurl = tf_InstanciaOrigen.getText();
            origindbname = tf_DBNameOrigen.getText();
            originport = tf_PuertoOrigen.getText();
            originuser = tf_UserOrigen.getText();
            originpass = tf_PassOrigen.getText();

            OracleConexion OC = new OracleConexion();
            Conexion1Y = OC.Conectar(originurl, originuser, originpass, originport);

            if (Conexion2Y) {
                //Logica para determinar que la conexion fue exitosa, pone los nombres de las tablas
                lbl_resultadoConexion1.setText("¡Conexion Exitosa!");
                lbl_resultadoConexion1.setForeground(Color.green);
                lbl_resultadoConexion1.setVisible(true);

                

            } else {
                lbl_resultadoConexion1.setText("¡Ha ocurrido un error!");
                lbl_resultadoConexion1.setForeground(Color.red);
                lbl_resultadoConexion1.setVisible(true);
            }

        } else if (radio_MYSQLOrigin.isSelected()) {

            //MYSQL
            originurl = tf_InstanciaOrigen.getText();
            origindbname = tf_DBNameOrigen.getText();
            originport = tf_PuertoOrigen.getText();
            originuser = tf_UserOrigen.getText();
            originpass = tf_PassOrigen.getText();

            ConexionMySQL MC = new ConexionMySQL();
            Conexion2Y = MC.conectar(originurl, originuser, originpass, originport, origindbname);

            if (Conexion2Y) {
                //Logica para determinar que la conexion fue exitosa, pone los nombres de las tablas
                lbl_resultadoConexion1.setText("¡Conexion Exitosa!");
                lbl_resultadoConexion1.setForeground(Color.green);
                lbl_resultadoConexion1.setVisible(true);

            } else {
                lbl_resultadoConexion1.setText("¡Ha ocurrido un error!");
                lbl_resultadoConexion1.setForeground(Color.red);
                lbl_resultadoConexion1.setVisible(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor, primero seleccione (arriba) si su base esta en Oracle o MYSQL");
        }
    }//GEN-LAST:event_btn_probarConDestinoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);

            }
        });
    }

    public void AbrirVentana(JDialog ventana) {
        ventana.pack();
        ventana.setModal(false);
        ventana.setLocationRelativeTo(this);
        ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_Ayuda;
    private javax.swing.JDialog JD_ConexionesDB;
    private javax.swing.ButtonGroup botonesDestino;
    private javax.swing.ButtonGroup botonesOrigen;
    private javax.swing.JButton btn_VolverAyuda;
    private javax.swing.JButton btn_cambiarDb;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_moveDeToOr;
    private javax.swing.JButton btn_moveOrToDe;
    private javax.swing.JButton btn_pedirAyuda;
    private javax.swing.JButton btn_probarConDestino;
    private javax.swing.JButton btn_probarConOrigen;
    private javax.swing.JButton btn_salirConexiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jl_tablasDbDe;
    private javax.swing.JList<String> jl_tablasDbOr;
    private javax.swing.JLabel lbl_resultadoConexion1;
    private javax.swing.JLabel lbl_resultadoConexion2;
    private javax.swing.JRadioButton radio_MYSQLDestination;
    private javax.swing.JRadioButton radio_MYSQLOrigin;
    private javax.swing.JRadioButton radio_ORACLEDestination;
    private javax.swing.JRadioButton radio_ORACLEOrigin;
    private javax.swing.JTextField tf_DBNameDestino;
    private javax.swing.JTextField tf_DBNameOrigen;
    private javax.swing.JTextField tf_InstanciaDestino;
    private javax.swing.JTextField tf_InstanciaOrigen;
    private javax.swing.JTextField tf_PassDestino;
    private javax.swing.JTextField tf_PassOrigen;
    private javax.swing.JTextField tf_PuertoDestino;
    private javax.swing.JTextField tf_PuertoOrigen;
    private javax.swing.JTextField tf_UserDestino;
    private javax.swing.JTextField tf_UserOrigen;
    // End of variables declaration//GEN-END:variables
}
